#!/bin/sh

# Set the directory where the notes are stored
NOTES_DIR="$HOME/notes"
# Set the editor to use
EDITOR="nvim"
# Set the file extension for the notes
EXTENSION="md"

# <<--------- Choosing Templates --------->>
Basic() {

    notify-send "Basic Document Created!"
    cd ~/Documents/Notes/
    cp ~/Documents/Notes/Templates/SimpleNote.md ~/Documents/Notes/"$note_name.md"
    nvim ~/Documents/Notes/"$note_name.md"
}

LaTeX() {

    notify-send "LaTeX Document Created!"
    cd ~/Documents/Notes/
    cp ~/Documents/Notes/Templates/LaTeX.tex ~/Documents/Notes/"$note_name.tex"
    nvim ~/Documents/Notes/"$note_name"/"$note_name.tex"
}

Presentation() {

    notify-send "Beamer Presentation Created!"
    cd ~/Documents/Notes/
    cp ~/Documents/Notes/Templates/Presentation.tex ~/Documents/Notes/"$note_name.tex"
    nvim ~/Documents/Notes/"$note_name"/"$note_name.tex"
}

RMark() {

    notify-send "R Markdown Document Created!"
    cd ~/Documents/Notes/
    cp ~/Documents/Notes/Templates/RMarkdown.rmd ~/Documents/Notes/"$note_name.rmd"
    nvim ~/Documents/Notes/"$note_name"/"$note_name.rmd"
}

template() {

    echo "1. Basic"
    echo "2. LaTeX"
    echo "3. R Markdown"
    echo "4. Presentation"
    read -p "Enter your choice: " TYPE
    case $TYPE in
        1) Basic ;;
        2) LaTeX ;;
        3) RMark ;;
        4) Presentation ;;
        *) echo "Invalid!" ;;
    esac
}

# <<--------- Main --------->>
create_note() {

    read -p "Enter the name of the note: " "note_name"
    if [ -f ~/Documents/Notes//$note_name.$EXTENSION ]; then
        echo "Note already exists"
        echo "1. Overwrite"
        echo "2. Cancel"
        read -p "Enter your choice: " choice
        case $choice in
            1) notify-send "New Note Created!" &&
            nvim ~/Documents/Notes//$note_name.$EXTENSION ;;
            2) main ;;
            *) echo "Invalid choice" ;;
        esac
    else
        template
    fi
}

view_note() {

    note=$(find ~/Documents/Notes/ -type f -name "*.$EXTENSION" | fzf --preview 'bat --color=always {}')
    if [ -z "$note" ]; then
        main
    else
        nvim "$note"
        view_note
    fi
}

delete_note() {

    note=$(find ~/Documents/Notes/ -type f -name "*.$EXTENSION" | fzf --preview 'bat --color=always {}')
    if [ -z "$note" ]; then
        main
    else
        rm $note
        echo "Note Removed!"
    fi
}

main() {

    # Check if the notes directory exists
    if [ ! -d ~/Documents/Notes/ ]; then
        mkdir ~/Documents/Notes/
    fi

    # Check if the notes directory is empty
    if [ ! "$(ls -A ~/Documents/Notes/)" ]; then
        echo "No notes found"
        echo "Creating a new note"
        create_note
    else
        echo "Notes found"
        echo "1. Create a new note"
        echo "2. View a note"
        echo "3. Delete a note"
        echo "4. Exit"
        read -p "Enter your choice: " choice

        case $choice in
            1) create_note ;;
            2) view_note ;;
            3) delete_note ;;
            4) exit 0 ;;
            *) echo "Invalid choice" ;;
        esac
    fi
}

main
